name: PageKite RDP TCP Tunnel

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  setup-rdp-tunnel:
    runs-on: windows-latest
    
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install PageKite
      run: |
        pip install pagekite
    
    - name: Configure Remote Desktop
      run: |
        # Aktifkan Remote Desktop
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        
        # Aktifkan Firewall RDP
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        
        # Konfigurasi Autentikasi RDP
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    
    - name: Set RDP Password
      run: |
        # Set password untuk akun runner
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd2024!" -Force)
    
    - name: Start PageKite Tunnel
      run: |
        # Jalankan PageKite untuk tunnel RDP
        Start-Process powershell -ArgumentList "-Command", "pagekite 3389 rdp-tunnel.pagekite.me" -PassThru
        
        # Tunggu inisialisasi tunnel
        Start-Sleep -Seconds 10
    
    - name: Display Connection Info
      run: |
        Write-Host "RDP Tunnel Created!"
        Write-Host "Connect to: rdp-tunnel.pagekite.me:3389"
        Write-Host "Username: runneradmin"
        Write-Host "Password: P@ssw0rd2024!"
    
    - name: Keep Workflow Alive
      run: |
        # Pertahankan workflow tetap berjalan
        while ($true) {
          Start-Sleep -Seconds 60
        }
