name: Free TCP Tunnel with Bore.pub

on: [push, workflow_dispatch]

jobs:
  setup-tcp-tunnel:
    runs-on: windows-latest
    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Install Bore
      run: npm install -g @boredome/cli
    
    - name: Enable Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    
    - name: Set RDP Password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    
    - name: Create Bore Tunnel
      run: |
        bore local 3389 &
        Start-Sleep -Seconds 10
        $boreProcess = Get-Process bore
        Write-Output "Bore Tunnel Running on PID: $($boreProcess.Id)"
    
    - name: Keep Tunnel Open
      run: |
        while ($true) {
          Start-Sleep -Seconds 60
        }
