name: Expose RDP TCP Tunnel

on:
  workflow_dispatch:
    push:
      branches:
        - main

jobs:
  setup-rdp-tunnel:
    runs-on: windows-latest
    steps:
      - name: Setup Expose
        run: |
          winget install expose
      - name: Configure Remote Desktop
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
      - name: Set RDP Password
        run: |
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd2024!" -Force)
      - name: Start Tunnel
        run: |
          expose tcp 3389
          echo "Link TCP: $(expose url)"
      - name: Keep Alive
        run: |
          while ($true) { Start-Sleep -Seconds 60 }
