name: Teleport RDP TCP Tunnel

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  setup-rdp-tunnel:
    runs-on: windows-latest
    
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Download and Install Teleport
      run: |
        Invoke-WebRequest -Uri "https://get.gravitational.com/teleport-v7.3.5-windows-amd64-bin.zip" -OutFile "teleport.zip"
        Expand-Archive -Path "teleport.zip" -DestinationPath "$env:USERPROFILE\teleport"
        $env:PATH += ";$env:USERPROFILE\teleport"

    - name: Verify Teleport Installation
      run: |
        dir "$env:USERPROFILE\teleport"
        Get-Command "$env:USERPROFILE\teleport\tsh.exe"

    - name: Configure Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    
    - name: Set RDP Password
      run: |
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd2024!" -Force)
    
    - name: Start Teleport Agent
      run: |
        & "$env:USERPROFILE\teleport\tsh.exe" tunnel --proxy=proxy.example.com --login=runneradmin --remote-port=3389 --local-port=6000

    - name: Display Tunnel Link
      run: |
        Write-Host "TCP Tunnel Link: proxy.example.com:6000"
    
    - name: Keep Alive
      run: |
        while ($true) {
          Start-Sleep -Seconds 60
        }
