name: Localtunnel RDP TCP Tunnel

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  setup-rdp-tunnel:
    runs-on: windows-latest
    
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install Localtunnel
      run: |
        npm install -g localtunnel
    
    - name: Configure Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    
    - name: Set RDP Password
      run: |
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd2024!" -Force)
    
    - name: Start Localtunnel and Display Link
      run: |
        lt --port 3389 --subdomain yourloverdp
    
    - name: Keep Alive
      run: |
        while ($true) {
          Start-Sleep -Seconds 60
        }
