name: Ncat RDP TCP Tunnel

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  setup-rdp-tunnel:
    runs-on: windows-latest
    
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Download and Install Ncat
      run: |
        choco install nmap -y
        $env:PATH += ";C:\Program Files (x86)\Nmap"
    
    - name: Configure Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    
    - name: Set RDP Password
      run: |
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd2024!" -Force)
    
    - name: Start Ncat Tunnel
      run: |
        ncat --sh-exec "ncat --exec 'cmd.exe' --allow 0.0.0.0" -l 3389 --keep-open
    
    - name: Display Tunnel Link
      run: |
        Write-Host "TCP Tunnel Link: localhost:3389"
    
    - name: Keep Alive
      run: |
        while ($true) {
          Start-Sleep -Seconds 60
        }
