name: LocalXpose RDP TCP Tunnel

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  setup-rdp-tunnel:
    runs-on: windows-latest
    
    steps:
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install LocalXpose
      run: |
        Invoke-WebRequest -Uri "https://localxpose.io/download/localxpose-v3.4.1-windows-amd64.zip" -OutFile "localxpose.zip"
        Expand-Archive -Path "localxpose.zip" -DestinationPath "$env:USERPROFILE\localxpose"
        $env:PATH += ";$env:USERPROFILE\localxpose"
    
    - name: Configure Remote Desktop
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    
    - name: Set RDP Password
      run: |
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd2024!" -Force)
    
    - name: Start LocalXpose Tunnel
      run: |
        localxpose.exe tcp --port 3389
    
    - name: Display Tunnel Link
      run: |
        Write-Host "TCP Tunnel Link: https://freerdplovesubedi.localxpose.io"
    
    - name: Keep Alive
      run: |
        while ($true) {
          Start-Sleep -Seconds 60
        }
